### ISSUE TITLE
'ProgbarLogger' object has no attribute 'log_values'

### ISSUE THREAD

**Issue by TheNitek** [AIWintermuteAI/transfer_learning_sipeed#2]
I'm trying to follow the instructables tutorial (on windows). Running test.py worked fine, but trying to running "python mbnet_keras.py" ends in

```
dense_3 (Dense)              (None, 2)                 102
=================================================================
Total params: 1,915,028
Trainable params: 82,052
Non-trainable params: 1,832,976
_________________________________________________________________
Epoch 1/10
Traceback (most recent call last):
  File "mbnet_keras.py", line 60, in <module>
    model.fit_generator(generator=train_generator,steps_per_epoch=step_size_train,epochs=10)
  File "C:\Users\Nitek\.conda\envs\ml\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Nitek\.conda\envs\ml\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\Nitek\.conda\envs\ml\lib\site-packages\keras\engine\training_generator.py", line 251, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "C:\Users\Nitek\.conda\envs\ml\lib\site-packages\keras\callbacks.py", line 79, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "C:\Users\Nitek\.conda\envs\ml\lib\site-packages\keras\callbacks.py", line 338, in on_epoch_end
    self.progbar.update(self.seen, self.log_values)
AttributeError: 'ProgbarLogger' object has no attribute 'log_values'
```

Any hints?

**Comment by AIWintermuteAI** [comment]
Hello! Yes, some other people also encountered this issue. Consult here  https://github.com/keras-team/keras/issues/3657

It might be possible your dataset is too small. How many images do you have? Are they in the right folder?

**Comment by TheNitek** [comment]
Yeah, I just realized that this project doesn't deliver example images, so I had 0 images which is of course a too small data set. Never mind ...
